[package]
name = "framp"
description = "Fork of James Miller's Ramp, a high-performance multiple-precision arithmetic library"
version = "0.3.7"
authors = ["James Miller <james@aatch.net>"]
build = "build.rs"
license = "Apache-2.0"
readme = "README.md"
keywords = ["bignum","math","number"]

repository = "https://github.com/snipsco/ramp"
documentation = "https://docs.rs/framp"

[lib]
name = "framp"
path = "src/lib.rs"

[features]
unstable = [] # To keep travis-cargo happy
fallbacks = []
asm = []

full-quickcheck = []

[dependencies]
ieee754 = "0.2"
rand = "0.3"
hamming = "0.1"
num-traits = "0.1.35"
num-integer = "0.1.32"
rust-gmp = { version = "0.2", optional = true }

[build-dependencies]
num-bigint = "0.1.35"
rustc-cfg = "0.2"
gcc = "0.3"

[dev-dependencies]
num-bigint = "0.1.35"
quickcheck = "0.4.1"
quickcheck_macros = "0.4.1"
